---
#global
ansible_shell_type: "sh" #for linux hosts only. On windows, override this variable on playbook with value "powershell"

#server docker
srv_hostname: "dockerlms"
srv_locale: "en_US.UTF-8"
srv_keymap: "br-abnt2"
srv_timezone: "America/Sao_Paulo"
srv_disks: 
  - sda

#lvm
lvmDisk: "/dev/sdb"
lvmGroup: "vg_docker"
lvmVolume: "vol_docker"
lvmMountPoint: "/var/lib/docker"

#proxy
enableproxy: true
prx_username: "{{ vault_proxy_user_name }}"
prx_domain: "{{ vault_proxy_domain }}"
prx_hash: "{{ vault_proxy_auth_hash }}"
prx_address: "{{ vault_proxy_address }}"
prx_port: "{{ vault_proxy_port }}"
prx_workstation: "{{ vault_proxy_workstation }}"
prx_noproxy: "localhost, 127.0.0.*, 10.*, 192.168.*, 172.*, {{ vault_proxy_noproxy }}"
prx_listenip: 0.0.0.0
prx_listenport: 3128
prx_gateway: "yes"

#docker daemon
dkr_composeversion: "1.23.2"
dkr_selinuxenabled: "false"
dkr_enabledebug: "true"
dkr_enabletls: "false"
dkr_tlscacertpath: ""
dkr_tlscertpath: ""
dkr_tlskeypath: ""
dkr_tlsverify: ""
dkr_logdriver: "json-file"
dkr_loglevel: "debug"
dkr_logmaxsize: "10m"
dkr_maxfile: "3"

#docker
dkr_host: "unix://var/run/docker.sock"
dkr_tls: no
dkr_host_binding_ipv4: "0.0.0.0"
dkr_ignore_image: yes
dkr_enableproxy: true
dkr_httpproxy: "http://127.0.0.1:3128"
dkr_httpsproxy: "http://127.0.0.1:3128"
dkr_noproxy: "localhost,127.0.0.1"
dkr_listenip: "0.0.0.0"
dkr_listenport: "2375"
######## STORAGE devicemapper config ########
#dkr_storagedriver: "devicemapper"
#dkr_storagefs: "xfs"
#dkr_thinpooldev: "/dev/mapper/docker-tpvolume"
#dkr_defremoval: true
#dkr_defdel: true
#############################################
########## STORAGE overlay2 config ##########
dkr_storagedriver: "overlay2"
dkr_storagefs: "xfs"
dkr_thinpooldev: ""
dkr_defremoval: ""
dkr_defdel: ""
#############################################

#mariadb
msql_port: "{{ vault_msql_db_port }}"
msql_socket: "/run/mysqld/mysqld.sock"
msql_storageengine: "innodb"
msql_tmpdir: "tmpdir"
msql_root_passwd: "{{ vault_msql_root_passwd }}"
msql_db: "{{ vault_msql_db_name }}"
msql_user: "{{ vault_msql_db_user }}"
msql_passwd: "{{ vault_msql_db_passwd }}"
msql_root_host: "%"
msql_log_console: "true"
msql_backup: "files/mysql.bkp"
msql_innodbbufferpoolsize: "64M"
msql_joinbuffersize: "64M"
msql_sortbuffersize: "2M"
msql_readrndbuffersize: "2M"
msql_logbin: "log_bin"
msql_skiphostcache: "skip-host-cache"
msql_skipnameresolve: "skip-name-resolve"
msql_logerror: "/var/log/mysqld.log"
msql_exec_user: "root"
msql_dumpfile: "limesurvey_dump_2019-04-02.sql"

#limesurvey
# lms_version: "3.15.5"
lms_version: "3.17.0"
lms_exec_user: "root"
lms_buildargs_http_proxy: "http://{{ ansible_eth0.ipv4.address }}:3128"
lms_virtualhost: "{{ vault_lms_virtualhost }}"
lms_virtualport: "80"
lms_httpsmethod: "nohttps"
lms_dbtype: "mysql"
lms_dbhost: "mariadb"
lms_dbport: "3306"
lms_dbname: "{{ vault_msql_db_name }}"
lms_dbtableprefix: "lime_"
lms_dbuser: "{{ vault_msql_db_user }}"
lms_dbpasswd: "{{ vault_msql_db_passwd }}"
lms_adminuser: "admin"
lms_adminname: "Administrator"
lms_adminemail: "{{ vault_lms_admin_email }}"
lms_adminpasswd: "{{ vault_lms_admin_passwd }}"