---
# tasks file for docker_service

- name: create config dir /etc/systemd/system/docker.service.d for docker service on Systemd
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0600
    owner: root
    group: root
  tags: docker_service

- name: Edit /etc/systemd/system/docker.service.d/http-proxy.conf and configure proxy options
  template: 
    src: http-proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    mode: 0644
    backup: no
    force: yes
  when: enableproxy
  tags:
    - docker_service

- name: Edit /etc/systemd/system/docker.service.d/hosts.conf and configure where Docker will listen
  template:
    src: host.conf.j2
    dest: /etc/systemd/system/docker.service.d/hosts.conf
    mode: 0644
    backup: no
    force: yes
  tags:
    - docker_service

- name: Reload daemon, enable and start Docker service
  systemd:
    name: docker
    state: started
    daemon_reload: yes
    enabled: yes
  tags:
    - docker_service

- name: start cntlm
  command: systemctl start cntlm
  when: enableproxy
  tags:
    - docker_service
    - proxy

- name: Test Docker installation and configuration
  docker_container:
    name: hello-world-test
    image: hello-world
  tags:
    - docker_service
    - docker-test

- name: Stop and remove test container
  docker_container:
    name: hello-world-test
    state: absent
  tags:
    - docker_service
    - docker-test

- name: stop cntlm
  command: systemctl stop cntlm
  when: enableproxy
  tags:
    - docker_service
    - proxy