---
[control]
vm-centos-7

[windows]
windows-server

[docker]

[control:vars]
ansible_connection=local

[windows:vars]
ansible_user=ansible
ansible_password="{{ vault_win_admin_passwd }}"
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_scheme=http
ansible_port=5985
ansible_winrm_server_cert_validation=ignore

[docker:vars]
ansible_user=ansible
ansible_password="{{vault_lnx_admin_passwd}}"