---
# tasks file for config

- name: configuration of all the system
  block: #config block

  - name: configure system language (locale)
    command: "localectl set-locale LANG={{ srv_locale }}"
    changed_when: false
    notify: reboot server

  - name: configure keymapping
    command: "localectl set-keymap {{ srv_keymap }}"
    changed_when: false
    notify: reboot server

  - name: set timezone
    timezone:
      name: "{{ srv_timezone }}"
    changed_when: false
    notify: reboot server

  - name: start cntlm
    systemd:
      name: cntlm
      state: started
    changed_when: false
    when: enableproxy

  - name: get all yum repo configuration files
    shell: "ls -1 /etc/yum.repos.d/ | grep -E 'CentOS|epel'"
    register: yumrepos
    changed_when: false

  - name: configure yum local repositories (baseurl)
    replace: 
      path: "/etc/yum.repos.d/{{ item }}"
      regexp: "^#baseurl="
      replace: "baseurl="
    with_items: "{{ yumrepos.stdout_lines }}"

  - name: configure yum local repositories (mirror list)
    replace: 
      path: "/etc/yum.repos.d/{{ item }}"
      regexp: "^mirrorlist="
      replace: "#mirrorlist="
    with_items: "{{ yumrepos.stdout_lines }}"
    
  - name: configure proxy for yum local repositories
    replace: 
      path: "/etc/yum.repos.d/{{ item }}"
      regexp: "^#proxy=_none_"
      replace: "proxy=_none_"
    with_items: "{{ yumrepos.stdout_lines }}"

  - name: clear yum cache
    shell: yum clean all
    args:
      warn: false
    changed_when: false
    
  - name: generate yum cache
    yum:
      update_cache: yes

  - name: update installed packages
    yum:
      update_only: yes
      update_cache: no

  - name: install pre-requisites
    yum:
      name: "{{ packages }}"
      state: present
      update_cache: no
    vars:
      packages:
        - wget
        - links
        - vim
        - htop
        - net-tools
        - libselinux-python
        - bash-completion
        - hyperv-daemons #integration services with hyper-v hypervisor

  - name: Enabling IP forward
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_set: yes
      state: present
      reload: yes
    notify: reboot server

  - name: set SELinux to permissive mode
    selinux:
      policy: targeted
      state: permissive
    notify: reboot server

  - name: stop and disable postfix
    systemd:
      name: postfix
      state: stopped
      enabled: no
    changed_when: false

  - name: enable dynamic memory on guest
    copy:
      dest: /etc/udev/rules.d/100-balloon.rules
      mode: 0774
      owner: root
      group: root
      content: |
        SUBSYSTEM=="memory", ACTION=="add", ATTR{state}="online"
      force: no
    notify: reboot server

  - name: disable disk io scheduler
    shell: "echo noop > /sys/block/{{ item }}/queue/scheduler"
    with_items: "{{ srv_disks }}"
    changed_when: false
    notify: reboot server

  always: #config block
    - name: stop cntlm
      systemd:
        name: cntlm
        state: stopped
      changed_when: false
      when: enableproxy

  tags: #config block
    - config