---
# tasks file for docker

- block:

  - name: install pre-requisites
    yum:
      name: "{{ packages }}"
      state: present
      update_cache: no
    vars:
      packages:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - python-docker-py
        - bash-completion
        - MySQL-python
        - mariadb

  - name: start cntlm
    command: systemctl start cntlm
    when: enableproxy
    changed_when: false

  - name: enable kernel user namespaces
    shell: 'grubby --args="namespace.unpriv_enable=1 user_namespace.enable=1" --update-kernel="$(grubby --default-kernel)"'
    notify: reboot docker server
    changed_when: false

  - name: config user namespaces max number
    copy: 
      dest: /etc/sysctl.d/user-namespaces.conf
      content: |
        user.max_user_namespaces=15000
      force: yes
      owner: root
    notify: reboot docker server
    changed_when: false

  - name: Populate service facts
    service_facts:

  - debug: var=ansible_facts.services

  - name: install docker-ce repo
    command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    when: "'docker.service' not in ansible_facts.services"
    changed_when: false

  - name: disable docker-ce repo
    command: yum-config-manager --disable docker-ce-stable
    changed_when: false

  - name: install docker-ce
    yum:
      enablerepo: docker-ce-stable
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    notify: reboot docker server
    when: "'docker.service' not in ansible_facts.services"

  - name: Ensure group "docker" exists
    group:
      name: docker
      state: present

  - name: adding existing user 'ansible' to group docker
    user:
      name: ansible
      groups: docker
      append: yes

  - name: stop cntlm
    command: systemctl stop cntlm
    when: enableproxy
    changed_when: false
  
  tags:
    - docker_install